### ISSUE TITLE
Test TPG FW candidate 2.1.0

### ISSUE THREAD

**Issue by jimbrooke** [DUNE-DAQ/flxlibs#35] opened 2022-04-25 13:19 UTC
Test FW patches to protect TPG against corrupt/partial input data.  Problems were observed previously using FELIX emulator, so first thing is to verify this no longer occurs.  Probably also useful to run with ZCU102 input source.

Suggest to use dunedaq-v2.11.0 release candidate, and generate config using : 
```python -m flxlibs.app_confgen -e -n 10 -t 2 -m "0,1,2,3,4,5:0,1,2,3,4,5" app_flx_12.json```

**Comment by kkothekar** [comment] 2022-04-28 20:57
I have replicated the lock-up issue (with firmware 2.0.0) and checked whether it is resolved in the latest firmware. **It seems to be resolved in the latest firmware.**
A report :

### Replication:
FW 2.0.0
DUNEDAQ 2.11

- Loaded the flx-emulator with FixedHits_A_emuconfig ( FixedHits_A formatted for emulator)
- Enabled the emulator
- Started fdaq stream
- Configured the chain and monitored the probes of the hit finding chain

The unpacker to hsc probe seems to remain busy all the time. I have changed the sequence, but every time ended up with the lock-up described in figure A.

![Figure_A_lock-upwith_FW2 0 0](https://user-images.githubusercontent.com/8162817/165844544-a66a1b4e-7706-4b1f-a59a-2d85da0b6424.png)

### Checking if the issue is resolved with the latest firmware:
FW 2.1.1
DUNEDAQ v2.11
Followed similar steps as above, but now the probes do not lock up the data keeps flowing across the chain. Changed the command sequence etc., and the probes did not lock up; please see Fig.B
![Figure_B_No_Lockup_withFW2 1 0](https://user-images.githubusercontent.com/8162817/165844689-e8e99053-0427-4329-92ba-03b1a068d8e1.png)

**Closed as completed** 2022-04-29 12:48 UTC
